@echo off
echo Starting stack...
docker compose up -d --build
echo Waiting 10 seconds...
timeout /t 10 >nul
echo Running demo calls...
REM Add your curl commands here if you have endpoints
echo Done. Open README for endpoints.
